### ISSUE TITLE
Wiki Seite für "Question"-Klassen

### ISSUE THREAD

**Issue by gelbeforelle** [gelbeforelle/SWE-SS21#15]
Kannst du bitte alle Infos zur Planung der Klassen für verschiedene Fragen auf einer Wiki-Seite darstellen? Quasi eine Seite anlegen mit den UML Diagrammen etc. die du bereits erstellt hast, damit man sie in der Readme verlinken kann.

**Comment by hannah-knst** [comment]
Ich habe eine Wiki-Seite dazu erstellt und in Readme unter [Punkt 2.2](https://github.com/gelbeforelle/SWE-SS21#22-konverter-f%C3%BCr-markierungen) verlinkt
