### ISSUE TITLE
Bug im Test Directory

### ISSUE THREAD

**Issue by gelbeforelle** [gelbeforelle/SWE-SS21#17]
Bitte teste, ob das Verzeichnis in den Tests funktioniert, ich habe den Namen der Testklasse geändert und dabei ein paar Probleme bei den Tests festgestellt

**Comment by hannah-knst** [comment]
Beim Testen wird der falsche Dateipfad erstellt und alle Tests schlagen fehl. Der pull request wird daher auch nicht angenommen.
Ich habe es eben sicherheitshalber nochmal im main-branch getestet, da funktioniert alles.
