### ISSUE TITLE
Nutzerdokumentation

### ISSUE THREAD

**Issue by gelbeforelle** [gelbeforelle/SWE-SS21#18]
Wir sollten uns überlegen, wie wir die Dokumentation für den Anwender gestalten.
Ich schlage vor, wir nutzen hierzu Doxygen. Ich werde ein Beispiel dazu vorbereiten.
Vielleicht kannst du dir überlegen, wie wir die Dateien von Doxygen (Grundlage html) veröffentlichen wollen?

Des Weiteren würde ich in die Dokumentation gerne Beispielcode einfügen. Vielleicht kannst du zum XmlParser und der fString/ Paragraph Klasse schon ein paar kurze Beispiele konzipieren.

**Comment by hannah-knst** [comment]
Mir sagt Doxygen bisher gar nichts, mir wäre das jetzt zu kurzfristig, mich da einzulesen.
Ich hätte in die Dokumentation auch keine Codebeispiele geschrieben, es geht doch erstmal nur darum, dass der Anwender weiß, wie er sein Word-Dokument zu formatieren hat, oder..?
Daher würde ich das ganze auch einfach als Word-Dokument schreiben (dann kann man es ja immer noch als pdf/webseite/... abspeichern)

**Comment by hannah-knst** [comment]
Mir sagt Doxygen bisher gar nichts, das wäre jetzt zu kurzfristig mich da einzulesen.
Ich würde das erstmal als .txt-Datei schreiben. Um eine schönere Dartsellung können wir uns kümmern, wenn wir am Ende noch Zeit haben^^

**Comment by gelbeforelle** [comment]
[Du kannst dich z.B. hier zu Doxygen und Dokumentation in C# belesen](https://github.com/TUBAF-IfI-LiaScript/VL_Softwareentwicklung/blob/master/17_Dokumentation_BuildTools.md).

Ich habe bereits damit angefangen und mal einen kleinen Vorschlag in dem Branch documentation hochgeladen.

**Comment by gelbeforelle** [comment]
Wollen wir die HTML Datei vielleicht über GitHub Pages hosten?

**Comment by gelbeforelle** [comment]
Nachdem ich deine Discord Nachricht als Fürspruch zur GH Page interpretiert habe, habe ich die Dateien (nach einigen Umwegen bei der Benennung) hochgeladen. Ich finde unsere kleine Website schon ganz cool. Wir haben sogar ein kleines Logo
https://gelbeforelle.github.io/SWE-SS21/
Ich denke, die Dokumentation ist schon ganz gut. Schau sie dir mal an, vielleicht findest du ja noch ein paar Stellen, wo man Beispielcode einfügen könnte.

Ansonsten habe ich die README.md der Dokumentation angepasst. Vergiss bitte den Wiki Eintrag nicht, der für die Readme noch aussteht. Wenn du mit der Dokumentation zufrieden bist, würde ich mich über einen schließenden Kommentar unter diesem Issue freuen.
