### ISSUE TITLE
Zusammenfassung, was alles (nicht) funktioniert

### ISSUE THREAD

**Issue by hannah-knst** [gelbeforelle/SWE-SS21#26]
Ich habe im readme-branch eine md-Datei dazu hochgeladen, was bisher alles funktioniert (-> [hier](https://github.com/gelbeforelle/SWE-SS21/blob/readme/WorkingFeatures.md)). Guck bitte drüber, ob das stimmt und ob noch Features fehlen.

Ich habe außerdem die Readme-Datei in dem branch aktualisiert.

**Comment by gelbeforelle** [comment]
Sieht gut aus. Ich habe noch ein paar Verbesserungen hinzugefügt, die ich doch noch heute morgen umsetzen konnte. Ansonsten passt das so. Wo wollen wir diese Datei speichern? Wollen wir sie in main ziehen und dort nur kurz in der README darauf verweisen?

**Comment by hannah-knst** [comment]
👍 
ich erstelle das nochmal als wiki-eintrag und verlinke es in der readme

**Comment by gelbeforelle** [comment]
Sehr gut. Das sollte so passen.
