### ISSUE TITLE
Zeit -und Aufgabenverteilung

### ISSUE THREAD

**Issue by hannah-knst** [gelbeforelle/SWE-SS21#5]
Ich habe wie besprochen ein [Wiki zur Aufgabenverteilung](https://github.com/gelbeforelle/SWE-SS21/wiki/Zeit--und-Aufgabenverteilung) angelegt. Ich habe versucht, die Aufgaben ein bisschen zu erklären, wenn da noch was fehlt oder was falsch ist, kannst du das gerne ergänzen.
Ich habe auch versucht den Zeitaufwand ganz grob abzuschätzen, da bin ich mir aber auch unsicher, ob das so hinkommt.
Das alte Wiki habe ich noch verlinkt, aber das kann gelöscht werden, da steht denke ich nichts zusätzlich drin..?

Wir können/sollten da auch regelmäßig den Stand der Bearbeitung eintragen. Man kann das auch noch in Planung und Implementierung aufteilen...

**Comment by gelbeforelle** [comment]
Ich werde den aktuellen Stand meiner Recherchen eintragen. Das Issue werden wir offen lassen, solange die genaue Planung noch nicht für alle Schritte abgeschlossen ist.

**Comment by gelbeforelle** [comment]
Da wir nun alles zugeteilt haben, was wir an Features vorhaben, wird das Issue geschlossen
